const menu = [
    {
      id: 1,
      title: "His House",
      category: "Horror",
      rating: 15.99,
      img: "./images/his-house..jpeg",
      desc: `righyt `,
    },
    {
      id: 2,
      title: "American Psycho",
      category: "Horror",
      rating: 13.99,
      img: "./images/item-2.jpeg",
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: "The cabin in the woods",
      category: "Horror",
      rating: 6.99,
      img: "./images/item-3.jpeg",
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: "As above so below",
      category: "Horror",
      rating: 20.99,
      img: "./images/item-4.jpeg",
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: "The lighthouse",
      category: "Horror",
      rating: 22.99,
      img: "./images/item-5.jpeg",
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: "Extracurriular",
      category: "Serie",
      rating: 18.99,
      img: "./images/item-6.jpeg",
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: "Criminal minds",
      category: "Serie",
      rating: 8.99,
      img: "./images/item-7.jpeg",
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: "All of us are dead",
      category: "Serie",
      rating: 12.99,
      img: "./images/item-8.jpeg",
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: " Nowhere girl",
      category: "Serie",
      rating: 16.99,
      img: "./images/item-9.jpeg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 10,
      title: "The uncanny counter",
      category: "Serie1",
      rating: 22.99,
      img: "./images/item-10.jpeg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
        id: 11,
        title: "The hobbit: An unexpected Jouney",
        category: "Fantasy",
        rating: 15.99,
        img: "./images/his-house..jpeg",
        desc: `righyt `,
      },
      {
        id: 12,
        title: "The hobbit: The desolation of smaug",
        category: "Fantasy",
        rating: 15.99,
        img: "./images/his-house..jpeg",
        desc: `righyt `,
      },
      {
        id: 13,
        title: "The hobbit: The battle of the five armies",
        category: "Fantasy",
        rating: 15.99,
        img: "./images/his-house..jpeg",
        desc: `righyt `,
      },
      {
        id: 14,
        title: "The lord of the rings: The fellowship of the ring",
        category: "Fantasy",
        rating: 15.99,
        img: "./images/his-house..jpeg",
        desc: `righyt `,
      },
      {
        id: 15,
        title: "The lord of the rings: The two towers",
        category: "Fantasy",
        rating: 15.99,
        img: "./images/his-house..jpeg",
        desc: `righyt `,
      },
      {
        id: 16,
        title: "The lord of the rings: The return of the king",
        category: "Fantasy",
        rating: 15.99,
        img: "./images/his-house..jpeg",
        desc: `righyt `,
      },
      {
        id: 17,
        title: "The witch:part1, Subversion",
        category: "Action",
        rating: 15.99,
        img: "./images/his-house..jpeg",
        desc: `righyt `,
      },
      {
        id: 18,
        title: "The gentelmen",
        category: "Action",
        rating: 15.99,
        img: "./images/his-house..jpeg",
        desc: `righyt `,
      },
      {
        id: 19,
        title: "Drive",
        category: "Action",
        rating: 15.99,
        img: "./images/his-house..jpeg",
        desc: `righyt `,
      },
      {
        id: 20,
        title: "The kingsman",
        category: "Action",
        rating: 15.99,
        img: "./images/his-house..jpeg",
        desc: `righyt `,
      },
  ];
  